openapi: 3.0.0
info:
  title: Blockstream API - Tip Height
  version: 1.0.0
paths:
  /blocks/tip/height:
    get:
      summary: Get height of the tip block from Blockstream API
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/block'
components:
  schemas:
    block:
      type: object
      properties:
        id:
          type: string
          description: ID of the block     