openapi: 3.0.0
info:
  title: Blockstream API - Tip Height
  version: 1.0.0
paths:
  /blocks/tip/height:
    get:
      summary: Get height of the tip block from Blockstream API
      description: Height of the tip block
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      item:
                        $ref: '#/components/schemas/AssetItem'
components:
  schemas:
    AssetItem:
      type: object
      properties:
        height:
          type: integer
